// mockConfidenceData.js
// Realistic mock data representing what Nivaran's document analysis would produce.
// Each item has: category, title, status (CONFIRMED/PARTIAL/MISSING),
// confidence %, source document, evidence found, missing information, and a suggested action.

export const mockConfidenceData = [
  {
    id: 'cl-1',
    category: 'Bank Accounts',
    title: 'SBI Savings Account',
    status: 'CONFIRMED',
    confidence: 94,
    sourceDocument: 'Bank Statement — SBI.pdf',
    evidence: [
      'Account number identified',
      'Branch details confirmed',
      'Nominee information found',
      'Last balance statement available',
    ],
    missingInfo: [],
    suggestedAction: 'Initiate account closure process with the branch.',
  },
  {
    id: 'cl-2',
    category: 'Bank Accounts',
    title: 'HDFC Current Account',
    status: 'PARTIAL',
    confidence: 72,
    sourceDocument: 'HDFC Passbook Scan.pdf',
    evidence: [
      'Account number identified',
      'Branch name found',
    ],
    missingInfo: [
      'Latest bank statement',
      'Nominee details not found',
    ],
    suggestedAction: 'Visit the HDFC branch with the death certificate to obtain the latest statement and nominee records.',
  },
  {
    id: 'cl-3',
    category: 'Insurance',
    title: 'LIC Term Life Policy',
    status: 'CONFIRMED',
    confidence: 91,
    sourceDocument: 'Life Insurance Policy.pdf',
    evidence: [
      'Policy number confirmed',
      'Sum assured identified',
      'Nominee is Aarti Sharma (Spouse)',
      'Premium payment history available',
    ],
    missingInfo: [],
    suggestedAction: 'File the insurance claim with LIC. Submission deadline identified in the policy.',
  },
  {
    id: 'cl-4',
    category: 'Insurance',
    title: 'Health Insurance — Family Floater',
    status: 'PARTIAL',
    confidence: 58,
    sourceDocument: 'Insurance Card Scan.jpg',
    evidence: [
      'Insurer name identified',
      'Policy number partially visible',
    ],
    missingInfo: [
      'Full policy document',
      'Coverage details',
      'Renewal date',
    ],
    suggestedAction: 'Contact the insurer to obtain a copy of the full policy document.',
  },
  {
    id: 'cl-5',
    category: 'Loans',
    title: 'Home Loan — ICICI Bank',
    status: 'PARTIAL',
    confidence: 68,
    sourceDocument: 'Loan Agreement.pdf',
    evidence: [
      'Loan agreement found',
      'Lender identified',
      'Account number identified',
    ],
    missingInfo: [
      'Latest repayment statement',
      'Closure/settlement amount',
      'Insurance cover on loan',
    ],
    suggestedAction: 'Request the latest loan statement and check if the loan has insurance cover.',
  },
  {
    id: 'cl-6',
    category: 'Credit Cards',
    title: 'Axis Bank Credit Card',
    status: 'MISSING',
    confidence: 12,
    sourceDocument: null,
    evidence: [
      'Reference found in a bank transaction narration',
    ],
    missingInfo: [
      'Credit card statement',
      'Outstanding balance',
      'Card number',
    ],
    suggestedAction: 'Contact Axis Bank to confirm if a credit card existed and request the final statement.',
  },
  {
    id: 'cl-7',
    category: 'Investments',
    title: 'Mutual Funds — SBI Bluechip',
    status: 'CONFIRMED',
    confidence: 89,
    sourceDocument: 'CAMS Statement.pdf',
    evidence: [
      'Folio number confirmed',
      'Fund name and units identified',
      'Nominee registered',
    ],
    missingInfo: [],
    suggestedAction: 'Submit transmission request to the fund house with required documents.',
  },
  {
    id: 'cl-8',
    category: 'Investments',
    title: 'PPF Account',
    status: 'CONFIRMED',
    confidence: 96,
    sourceDocument: 'PPF Passbook.pdf',
    evidence: [
      'Account number confirmed',
      'Maturity date known',
      'Nominee registered',
      'Balance verified',
    ],
    missingInfo: [],
    suggestedAction: 'Apply for premature closure or transfer at the post office / bank.',
  },
  {
    id: 'cl-9',
    category: 'Tax Documents',
    title: 'Income Tax Returns — AY 2023-24',
    status: 'PARTIAL',
    confidence: 65,
    sourceDocument: 'ITR Acknowledgement.pdf',
    evidence: [
      'PAN number confirmed',
      'Filing acknowledgement found',
    ],
    missingInfo: [
      'Full ITR document with schedules',
      'Form 16 / 16A',
      'Capital gains details',
    ],
    suggestedAction: 'Download the complete ITR from the Income Tax portal using the PAN and registered credentials.',
  },
  {
    id: 'cl-10',
    category: 'Tax Documents',
    title: 'Final Year Tax Filing',
    status: 'MISSING',
    confidence: 0,
    sourceDocument: null,
    evidence: [],
    missingInfo: [
      'Income details for the final partial year',
      'TDS certificates',
      'Tax computation',
    ],
    suggestedAction: 'Engage a CA to file the final return for the deceased on behalf of the legal heir.',
  },
  {
    id: 'cl-11',
    category: 'Property',
    title: 'Residential Flat — Pune',
    status: 'CONFIRMED',
    confidence: 88,
    sourceDocument: 'Sale Deed — Pune Flat.pdf',
    evidence: [
      'Property registration details confirmed',
      'Ownership name matches deceased',
      'Society NOC available',
    ],
    missingInfo: [
      'Latest property tax receipt',
    ],
    suggestedAction: 'Initiate mutation of property records at the local municipal office.',
  },
  {
    id: 'cl-12',
    category: 'Property',
    title: 'Agricultural Land — Nashik',
    status: 'MISSING',
    confidence: 15,
    sourceDocument: null,
    evidence: [
      'Mentioned in a will document',
    ],
    missingInfo: [
      '7/12 extract',
      'Land survey number',
      'Exact location and area',
    ],
    suggestedAction: 'Visit the Talathi office in Nashik to obtain the 7/12 extract and verify ownership records.',
  },
];
