// mockTimelineData.js
// Realistic mock data representing deadlines and tasks extracted from financial documents.
// Each item has: date, title, description, category, priority, status,
// source document, assigned person, and evidence/reasoning.

export const mockTimelineData = [
  {
    id: 'tl-1',
    date: '2026-09-28',
    title: 'Insurance claim deadline',
    description: 'Submit required documents for the LIC term life insurance claim. The policy specifies a submission window from the date of death.',
    category: 'Insurance',
    priority: 'HIGH',
    status: 'PENDING',
    sourceDocument: 'Life Insurance Policy.pdf',
    assignedTo: 'Aarti Sharma',
    reasoning: 'Claim submission window identified in the policy document. Filing within 90 days of death is recommended to avoid complications.',
  },
  {
    id: 'tl-2',
    date: '2026-10-04',
    title: 'Loan settlement document required',
    description: 'Obtain the latest repayment statement and settlement amount from ICICI Bank for the outstanding home loan.',
    category: 'Loans',
    priority: 'HIGH',
    status: 'PENDING',
    sourceDocument: 'Loan Agreement.pdf',
    assignedTo: 'Rohan Sharma',
    reasoning: 'Loan agreement indicates periodic settlement review. An updated statement is needed before initiating the closure process.',
  },
  {
    id: 'tl-3',
    date: '2026-10-12',
    title: 'Bank account closure follow-up',
    description: 'Follow up with SBI branch on the savings account closure application submitted earlier.',
    category: 'Bank Accounts',
    priority: 'MEDIUM',
    status: 'PENDING',
    sourceDocument: 'Bank Statement — SBI.pdf',
    assignedTo: 'Aarti Sharma',
    reasoning: 'Typical bank account closure processing takes 2–4 weeks. A follow-up ensures the process is not stalled.',
  },
  {
    id: 'tl-4',
    date: '2026-10-18',
    title: 'Mutual fund transmission request',
    description: 'Submit the transmission form to SBI Mutual Fund along with the death certificate, nominee KYC, and folio details.',
    category: 'Investments',
    priority: 'MEDIUM',
    status: 'PENDING',
    sourceDocument: 'CAMS Statement.pdf',
    assignedTo: 'Rohan Sharma',
    reasoning: 'CAMS statement confirms Rohan Sharma as nominee. Transmission can be initiated once supporting documents are gathered.',
  },
  {
    id: 'tl-5',
    date: '2026-10-25',
    title: 'Tax document collection',
    description: 'Collect Form 16, TDS certificates, and other tax documents needed for the final year tax filing.',
    category: 'Tax Documents',
    priority: 'MEDIUM',
    status: 'PENDING',
    sourceDocument: 'ITR Acknowledgement.pdf',
    assignedTo: 'Priya Desai',
    reasoning: 'The ITR acknowledgement indicates previous filing. The CA (Priya Desai) needs the supporting documents to prepare the final return.',
  },
  {
    id: 'tl-6',
    date: '2026-11-01',
    title: 'Property mutation application',
    description: 'Submit the property mutation application at the Pune municipal office to transfer the flat ownership.',
    category: 'Property',
    priority: 'MEDIUM',
    status: 'PENDING',
    sourceDocument: 'Sale Deed — Pune Flat.pdf',
    assignedTo: 'Aarti Sharma',
    reasoning: 'Sale deed confirms ownership. Mutation should be initiated early as the process can take several weeks to months.',
  },
  {
    id: 'tl-7',
    date: '2026-11-15',
    title: 'PPF account closure application',
    description: 'Apply for premature closure of the PPF account at the post office / bank. Nominee documentation required.',
    category: 'Investments',
    priority: 'LOW',
    status: 'PENDING',
    sourceDocument: 'PPF Passbook.pdf',
    assignedTo: 'Rohan Sharma',
    reasoning: 'PPF passbook confirms nominee. This can be done after higher-priority items but should not be delayed indefinitely.',
  },
  {
    id: 'tl-8',
    date: '2026-09-20',
    title: 'Death certificate obtained',
    description: 'Official death certificate collected from the municipal authority.',
    category: 'Legal',
    priority: 'HIGH',
    status: 'COMPLETED',
    sourceDocument: null,
    assignedTo: 'Aarti Sharma',
    reasoning: 'Required for all subsequent financial closure actions.',
  },
];
